### ISSUE TITLE
ZADANIE: Wizualizacja planszy 2D (IBoard<>) przez eksport grafiki

### ISSUE THREAD

**Issue by kgumk** [j4nw/siwg2019#19]
Zrzut planszy do pliku graficznego przy pomocy klasy System.Drawing.Image.

**Comment by j4nw** [comment]
Zaimplementowałem, przykład użycia w `WorldGeneration.CLI`, tutaj dla prostej heightmapy + wody:

![heightmap](https://user-images.githubusercontent.com/26443707/54767089-c4f8eb00-4bfc-11e9-87a1-8c29507dc772.png)
